### ISSUE TITLE
pillager patrols dont seem to be affected by lowered despawn distance

### ISSUE THREAD

**Issue by JumperREDACTED** [vlad2305m/Proper-Mobcap-Modifier#6]
![image](https://user-images.githubusercontent.com/83337894/176882046-a3190e66-2cf8-4fb9-9379-6d6ab0bc930c.png)

blue sphere is my set despawn distance (100), red sphere is vanilla

from the little testing i did, it seems like they in fact despawn only when you are around 150 blocks away

server log: https://mclo.gs/Vvu1A6T

**Comment by vlad2305m** [comment]
`PatrolEntity.class` :
```java
public boolean canImmediatelyDespawn(double distanceSquared) {
        return !this.patrolling || distanceSquared > 16384.0D;
    }
```
(16384 = 128²)
This is Minecraft's intantional behaivor for mobs on duty. What did you expect?

**Comment by vlad2305m** [comment]
BTW there already is a check on the SpawnGroup's value before this check, so you can increase the radius with the settings, but not decrease it below 128 as it is double-checked for some reason.

**Comment by JumperREDACTED** [comment]
> `PatrolEntity.class` :
> 
> ```java
> public boolean canImmediatelyDespawn(double distanceSquared) {
>         return !this.patrolling || distanceSquared > 16384.0D;
>     }
> ```
> 
> (16384 = 128²) This is Minecraft's intantional behaivor for mobs on duty. What did you expect?

well, i expected the mod to reduce the despawn radius

**Comment by vlad2305m** [comment]
To keep the simplicity, I will not fix vanilla Minecraft bugs
